
# 1. Fix FFmpeg (Create avconfig.h)
$ffmpegDir = "C:\Dev\FFmpeg\ffmpeg-5.0\libavutil"
if (-not (Test-Path $ffmpegDir)) { New-Item -Path $ffmpegDir -ItemType Directory -Force }

$avconfigContent = @"
/* Generated by manual script for Mine-imator build compatibility */
#ifndef AVUTIL_AVCONFIG_H
#define AVUTIL_AVCONFIG_H
#define AV_HAVE_BIGENDIAN 0
#define AV_HAVE_FAST_UNALIGNED 1
#endif /* AVUTIL_AVCONFIG_H */
"@
Set-Content -Path "$ffmpegDir\avconfig.h" -Value $avconfigContent
Write-Host "Fixed: avconfig.h created."

# 2. Fix Libzip (Create zipconf.h)
# Libzip headers include <zipconf.h> but in source it is usually cmake-generated. 
# We will create a generic one for Windows/MSVC.
$libzipDir = "C:\Dev\Libzip\libzip-1.9.2\lib"
if (-not (Test-Path $libzipDir)) { New-Item -Path $libzipDir -ItemType Directory -Force }

$zipconfContent = @"
#ifndef _HAD_ZIPCONF_H
#define _HAD_ZIPCONF_H

/* Valid for Windows MSVC (64-bit assumption based on current build) */

#define LIBZIP_VERSION "1.9.2"
#define LIBZIP_VERSION_MAJOR 1
#define LIBZIP_VERSION_MINOR 9
#define LIBZIP_VERSION_MICRO 2

#include <inttypes.h>

typedef int8_t zip_int8_t;
typedef uint8_t zip_uint8_t;
typedef int16_t zip_int16_t;
typedef uint16_t zip_uint16_t;
typedef int32_t zip_int32_t;
typedef uint32_t zip_uint32_t;
typedef int64_t zip_int64_t;
typedef uint64_t zip_uint64_t;

#define ZIP_INT8_MIN INT8_MIN
#define ZIP_INT8_MAX INT8_MAX
#define ZIP_UINT8_MAX UINT8_MAX
#define ZIP_INT16_MIN INT16_MIN
#define ZIP_INT16_MAX INT16_MAX
#define ZIP_UINT16_MAX UINT16_MAX
#define ZIP_INT32_MIN INT32_MIN
#define ZIP_INT32_MAX INT32_MAX
#define ZIP_UINT32_MAX UINT32_MAX
#define ZIP_INT64_MIN INT64_MIN
#define ZIP_INT64_MAX INT64_MAX
#define ZIP_UINT64_MAX UINT64_MAX

#endif /* _HAD_ZIPCONF_H */
"@
Set-Content -Path "$libzipDir\zipconf.h" -Value $zipconfContent
Write-Host "Fixed: zipconf.h created."

# 3. Fix FreeType (ft2build.h check)
# Sometimes freetype expects <ft2build.h> directly in include root.
if (Test-Path "C:\Dev\FreeType\freetype-2.9.1\include\ft2build.h") {
    # It's usually fine, but CMake config adds "include" to path.
    # Code usually does #include <ft2build.h>
    Write-Host "FreeType struct looks OK."
}

Write-Host "Header fixes applied."
